one = raw_input("Give me an ajective")
two = raw_input("Give me a noun")
three = raw_input("Give me a plural noun")
four = raw_input("Give me a female in the room")
five = raw_input("Give me an adjective")
six = raw_input("Give me an article of clothing")
seven = raw_input("Give me a noun")
eight = raw_input("Give me a city")
nine = raw_input("Give me a plural noun")
ten = raw_input("Give me an adjective")
eleven = raw_input("Give me a part of the body")
twelve = raw_input("Give me a letter of the alphabet")
thirteen = raw_input("Give me a celebrity")
fourteen = raw_input("Give me a plural noun")
fifteen = raw_input("Give me an adjective")
sixteen = raw_input("Give me a place")
seventeen = raw_input("Give me a part of the body")
eighteen = raw_input("Give me an adjective")
nineteen = raw_input("Give me an adjective")
twenty = raw_input("Give me a verb")
twentyone = raw_input("Give me a plural noun")
twentytwo = raw_input("Give me a number")

print "There are many" , one , "ways to choose a/an" , two , "to read. First, you could ask for recommendations from your friends and" , three + ". Just don't ask Aunt" , four + "--she only reads" , five , "books with" , six + "- ripping goddesses on the cover. If your friends and family are no help, try checking out the" , seven , "Review in The" , eight , "Times. If the" , nine , "featured there are too" , ten , "for your taste, try something a little more low-" + eleven , ",like" , twelve , ": The" , thirteen , "Magazine, or" , fourteen , 
print "Magazine. You could also choose a book the" , fifteen + "-fashioned way. Head to your local library or" , sixteen , "and browse the shelves until something catches your" , seventeen + ". Or, you could save yourself a whole lot of" , eighteen , "trouble and log onto bookish.com, the" , nineteen , "new website to" , twenty , "for books! With all the time you'll save not having to search for" , twentyone , "you can read" , twentytwo , "more books!"